### ISSUE TITLE
Blog, reply to comment, comments vanish

### ISSUE THREAD

**Issue by bsevening** [blueriver/MuraFoundation5Bundle#1]
Mura 6.1, CF 9. I started with the Bootstrap theme of course then switched to Foundation5. When I reply to a comment already in the system my comments all vanish. If I switch my theme back to Bootstrap I get my comments back. Also no matter what theme I have in place Modules/Comment Manager just hangs when trying to load it. Probably not even related to the vanishing comments. So not sure whats up with that.

This is my development box which is Open Suse 11, with MYSQL 5.5, and Apache.

**Comment by bsevening** [comment]
Little more info, didn't realize at first it was using Ajax. Found JS error and here's the error server returning.

default/includes/display_objects/comments/ajax/commentsProxy.cfc:233
Element COMMENTMORECOMMENTSCONTAINER is undefined in RENDERER

**Comment by bsevening** [comment]
Should have let you have the method call also.

commentsProxy.cfc?method=renderCommentsPage&contentID=E94A1DE1-0CE2-4431-879CAAF918F22C3D&sortDirection=desc&nextN=3

**Comment by seanschroeder** [comment]
Can you try updating both the Mura core and site and see if it still exists?

**Comment by bsevening** [comment]
Didn't work, had high hopes when it updated /comments/ajax/commentsProxy.cfc.

Looks like one of the following is getting out of sync.
<cfif it.getPageIndex() lt it.pageCount()>

I would think they should both have the same value as I only have 4 comments.

**Comment by bsevening** [comment]
Well narrowed it down a bit more. Line 239 commentsproxy

1 -- pageindex
2 -- pagecount

**Comment by mattlevine** [comment]
It looks like commentMoreCommentsContainer is not in the base renderer.

**Comment by bsevening** [comment]
Well that seems to have did the trick, added this.commentMoreCommentsContainer=""; to MuraFoundation5/contentRenderer.cfc. One thing that baffles me is I have the blog folder set to display 10 records per page but I only get three, now I know why the pagecount is 2.

**Comment by bsevening** [comment]
Figured out my modules/comment manager issue, probably not a foundation5 issue but hopefully you guys can get it where it needs to go. It was another JS issue, code was looking for file loadcomments.cfc, file was named loadComments.cfc. Doesn't work on a linux box. You can wax this of course if it's not relevant.

Thanks for all your help guys.
